### ISSUE TITLE
configure quay build trigger

### ISSUE THREAD

**Issue by goern** [thoth-station/httpd-aicoe-container#1] opened 2018-08-08 07:54 UTC
We need to configure a quay build trigger at https://quay.io/repository/aicoe/s2i-httpd-tensorflow-index?tab=builds so that the image gets rebuild whenever something is pushed to master of this repo.

problem: quay does not see thoth-station repos...

**Comment by harshad16** [comment] 2018-08-27 19:02
@goern I had a conversation with Vasek. He had looked into the problem, the reason quay build triggers are failing is that quay is not able to find the Dockerfile in 2.4/ dirs even if specified while building the trigger.  vasek said he would notify quay people about the issue. Until then:
The alternative to fix the issue is to move the Dockerfile outside of 2.4/ directory.

**Comment by harshad16** [comment] 2018-09-05 14:36
@goern Should I close the issue?

**Comment by goern** [comment] 2018-09-05 16:51
Ah hmm I think for zuul-test-infra I'm using the exact same pattern, and it builds :/

**Comment by harshad16** [comment] 2019-04-23 13:28
We are manually triggering the quay build for the httpd-aicoe-container.
Closing the Issue, for now, if in future, we require the feature, this issue can be reopened then. :+1:

**Closed as completed by harshad16** 2019-04-23 13:28 UTC
